// <auto-generated />
using System;
using KhaoSatBep.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KhaoSatBep.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512032034_TaoFullCSDL")]
    partial class TaoFullCSDL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KhaoSatBep.API.Models.Bep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiBep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenBep")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Beps");
                });

            modelBuilder.Entity("KhaoSatBep.API.Models.BienBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuaAnDuongMieng")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BuaAnOngThong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GopYKhoaDinhDuong")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("LoaiBienBan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKiemTra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("SoBienBan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ThucDonHangNgay")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ChuaGui");

                    b.Property<string>("YKienBPCB")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("LoaiBienBan");

                    b.HasIndex("NgayKiemTra");

                    b.HasIndex("NguoiTaoId");

                    b.HasIndex("TrangThai");

                    b.ToTable("BienBans");
                });

            modelBuilder.Entity("KhaoSatBep.API.Models.ChiTietBienBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BienBanId")
                        .HasColumnType("int");

                    b.Property<bool?>("Dat")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MucSo")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhanNhom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BienBanId");

                    b.HasIndex("MucSo");

                    b.ToTable("ChiTietBienBans");
                });

            modelBuilder.Entity("KhaoSatBep.API.Models.ChiTietKhaoSat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Diem")
                        .HasColumnType("int");

                    b.Property<string>("HangMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhaoSatId")
                        .HasColumnType("int");

                    b.Property<string>("NhanXet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KhaoSatId");

                    b.ToTable("ChiTietKhaoSats");
                });

            modelBuilder.Entity("KhaoSatBep.API.Models.ChuKy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BienBanId")
                        .HasColumnType("int");

                    b.Property<string>("ChucVuNguoiKy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DuLieuChuKy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenNguoiKy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BienBanId");

                    b.ToTable("ChuKys");
                });

            modelBuilder.Entity("KhaoSatBep.API.Models.DinhLuongSuatAn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BienBanId")
                        .HasColumnType("int");

                    b.Property<bool?>("CheDoAn1Dat")
                        .HasColumnType("bit");

                    b.Property<double?>("CheDoAn1KhoiLuong")
                        .HasColumnType("float");

                    b.Property<bool?>("CheDoAn1KhongDat")
                        .HasColumnType("bit");

                    b.Property<string>("CheDoAn1Ten")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("CheDoAn2Dat")
                        .HasColumnType("bit");

                    b.Property<double?>("CheDoAn2KhoiLuong")
                        .HasColumnType("float");

                    b.Property<bool?>("CheDoAn2KhongDat")
                        .HasColumnType("bit");

                    b.Property<string>("CheDoAn2Ten")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoaiSuatAn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("STT")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BienBanId");

                    b.ToTable("DinhLuongSuatAns");
                });

            modelBuilder.Entity("KhaoSatBep.API.Models.KhaoSat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BepId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayKhaoSat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiKhaoSatId")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BepId");

                    b.HasIndex("NguoiKhaoSatId");

                    b.ToTable("KhaoSats");
                });

            modelBuilder.Entity("KhaoSatBep.API.Models.ThanhPhanKiemTra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BienBanId")
                        .HasColumnType("int");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("STT")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BienBanId");

                    b.ToTable("ThanhPhanKiemTras");
                });

            modelBuilder.Entity("KhaoSatBep.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("NguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@khaosatbep.vn",
                            HoTen = "Quản Trị Viên",
                            MatKhauHash = "$2a$11$PdFWfiloDUL0W70wTkq/lulgqO.UlBFQciWyGi0FAdqITjGhrq95K",
                            NgayTao = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VaiTro = "Admin"
                        });
                });

            modelBuilder.Entity("KhaoSatBep.API.Models.BienBan", b =>
                {
                    b.HasOne("KhaoSatBep.API.Models.User", "NguoiTao")
                        .WithMany("BienBans")
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("KhaoSatBep.API.Models.ChiTietBienBan", b =>
                {
                    b.HasOne("KhaoSatBep.API.Models.BienBan", "BienBan")
                        .WithMany("ChiTiets")
                        .HasForeignKey("BienBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BienBan");
                });

            modelBuilder.Entity("KhaoSatBep.API.Models.ChiTietKhaoSat", b =>
                {
                    b.HasOne("KhaoSatBep.API.Models.KhaoSat", "KhaoSat")
                        .WithMany("ChiTiets")
                        .HasForeignKey("KhaoSatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhaoSat");
                });

            modelBuilder.Entity("KhaoSatBep.API.Models.ChuKy", b =>
                {
                    b.HasOne("KhaoSatBep.API.Models.BienBan", "BienBan")
                        .WithMany("ChuKys")
                        .HasForeignKey("BienBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BienBan");
                });

            modelBuilder.Entity("KhaoSatBep.API.Models.DinhLuongSuatAn", b =>
                {
                    b.HasOne("KhaoSatBep.API.Models.BienBan", "BienBan")
                        .WithMany("DinhLuongs")
                        .HasForeignKey("BienBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BienBan");
                });

            modelBuilder.Entity("KhaoSatBep.API.Models.KhaoSat", b =>
                {
                    b.HasOne("KhaoSatBep.API.Models.Bep", "Bep")
                        .WithMany("KhaoSats")
                        .HasForeignKey("BepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KhaoSatBep.API.Models.User", "NguoiKhaoSat")
                        .WithMany("KhaoSats")
                        .HasForeignKey("NguoiKhaoSatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bep");

                    b.Navigation("NguoiKhaoSat");
                });

            modelBuilder.Entity("KhaoSatBep.API.Models.ThanhPhanKiemTra", b =>
                {
                    b.HasOne("KhaoSatBep.API.Models.BienBan", "BienBan")
                        .WithMany("ThanhPhans")
                        .HasForeignKey("BienBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BienBan");
                });

            modelBuilder.Entity("KhaoSatBep.API.Models.Bep", b =>
                {
                    b.Navigation("KhaoSats");
                });

            modelBuilder.Entity("KhaoSatBep.API.Models.BienBan", b =>
                {
                    b.Navigation("ChiTiets");

                    b.Navigation("ChuKys");

                    b.Navigation("DinhLuongs");

                    b.Navigation("ThanhPhans");
                });

            modelBuilder.Entity("KhaoSatBep.API.Models.KhaoSat", b =>
                {
                    b.Navigation("ChiTiets");
                });

            modelBuilder.Entity("KhaoSatBep.API.Models.User", b =>
                {
                    b.Navigation("BienBans");

                    b.Navigation("KhaoSats");
                });
#pragma warning restore 612, 618
        }
    }
}
